name: Pull Request
on:
  pull_request:
    branches:
			- main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip3 install -r requirements-dev.txt
      - run: pytest
      - run: black iac tests --check
      - run: flake8 iac tests
